name: presubmit
on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:
  test:
    name: cargo test --all-features
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: moonrepo/setup-rust@b8edcc56aab474d90c7cf0bb8beeaf8334c15e9f
        with:
          channel: '1.74.0'
      - run: sudo apt-get install libpam0g-dev
      - run: cargo test --all-features

        # TODO: miri has trouble with some of our IO, I think the re-exec causes issues
        # miri:
        #   name: cargo +nightly miri test
        #   runs-on: ubuntu-22.04
        #   steps:
        #     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        #     - uses: moonrepo/setup-rust@b8edcc56aab474d90c7cf0bb8beeaf8334c15e9f
        #       with:
        #         components: miri
        #         channel: nightly
        #     - run: sudo apt-get install libpam0g-dev
        #     - run: MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test

  rustfmt:
    name: cargo +nightly fmt -- --check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: moonrepo/setup-rust@b8edcc56aab474d90c7cf0bb8beeaf8334c15e9f
        with:
          components: rustfmt
          channel: nightly
      - run: cargo +nightly fmt -- --check

  cranky:
    name: cargo +nightly cranky --all-targets -- -D warnings
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy
          bins: cargo-cranky@0.3.0
          channel: nightly
      - run: sudo apt-get install libpam0g-dev
      - run: cargo +nightly cranky --all-targets -- -D warnings

  deny:
    name: cargo deny --all-features check licenses
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: moonrepo/setup-rust@b8edcc56aab474d90c7cf0bb8beeaf8334c15e9f
        with:
          channel: '1.74.0'
          bins: cargo-deny
      - run: sudo apt-get install libpam0g-dev
      - run: cargo deny --all-features check licenses
